// Unity sentence pool — every word must resolve to a sign in SignController.cs
// (HELLO, BOOK, CLASS, COFFEE, TOMORROW, PLEASE, TAKE, THIS, WHERE, WHICH,
//  EVERYONE, MY, YOU, ANCIENT, ALIEN, ANGEL, ANIMAL, ANSWER, ANY, BABY, BAG,
//  BANANA, CAMERA, CHILD, DAD, DANGER, AND, OR, COME, BAD, BALANCE, FUTURE,
//  EQUAL, COFFEE, APPLE, ANNOY, ANIMAL, ANGEL, BAKE, BALANCE, ARRIVE, etc.)
export const UNITY_RANDOM_SENTENCES = [
  'Hello, everyone in class.',
  'Please take this book to class tomorrow.',
  'Tomorrow, please take my book to class.',
  'Is this your book for class tomorrow?',
  'Which book will you take tomorrow?',
  'Where will you take this book tomorrow?',
  'Please take coffee to class tomorrow.',
  'My child, please take this book.',
  'This ancient book is for my child.',
  'Tomorrow, everyone should take a book.',
  'Which book should everyone take to class?',
  'Hello, please take this book.',
  'This book is ancient and important.',
  'This alien book looks ancient.',
  'Please take this coffee to everyone.',
  'Tomorrow, this class needs a book.',
  'Where is my book for class tomorrow?',
  'Which class is tomorrow for you?',
  'Please take this book for everyone.',
  'This book is for you and my child.',
  'Everyone, please take this book tomorrow.',
  'Hello, which book is for class tomorrow?',
  'This coffee is for everyone tomorrow.',
  'Please take this ancient book to class.',
  'Where should my child take this book?',
  'Tomorrow, please take coffee and a book.',
  'Is this ancient book for class tomorrow?',
  'Which book is for you tomorrow?',
  'Please take this book and this coffee.',
  'Hello, everyone, this class is tomorrow.',
  'Is the class tomorrow?',
  'Is this your book?',
  'Which book is yours?',
  'Where is this book?',
  'Tomorrow, everyone is ready for class.',
  'Please take this bag and this book.',
  'My dad has an ancient camera.',
  'This baby has a banana and a bag.',
  'The angel and the alien are here.',
  'This animal is near the camp.',
  'The dandelion is near the camp.',
  'The danger is near the camp.',
  'The future class needs another book.',
  'Any child can take this book.',
  'Please answer this ancient question.',
  'This balance is important for class.',
  'Hello, how are you today?',
  'Please help me with this book.',
  'Where is my coffee?',
  'Is this class for you?',
  'My child needs this book.',
  'Please bring coffee to class.',
  'Is this your coffee?',
  'Which book do you need?',
  'This is my book.',
  'Please come here tomorrow.',
  'Where are you going tomorrow?',
  'This is for my child.',
  'Where is everyone today?',
  'My camera is in this bag.',
  'Please bring my bag tomorrow.',
  'This banana is for my child.',
  'Please take this camera.',
  'Everyone is here for class.',
  'Where is my bag?',
] as const;

// Video sentence pool — every word must have a matching clip in /public/signs/
// Uses the WLASL video dataset vocabulary (2000 words including common everyday words)
export const VIDEO_RANDOM_SENTENCES = [
  'Hello, how are you today?',
  'What time is it?',
  'Where is the bathroom?',
  'Please help me.',
  'I am happy today.',
  'I do not understand.',
  'Thank you.',
  'I love you.',
  'I want to go to the store tomorrow.',
  'Please come here.',
  'Where are you going tomorrow?',
  'I want coffee.',
  'I am ready for class.',
  'Can you help me now?',
  'Today I want water.',
  'Tomorrow we go to school.',
  'Where is your book?',
  'I need help with this.',
  'What do you want?',
  'Who is your teacher?',
  'When is class?',
  'I am tired today.',
  'Are you happy now?',
  'Please look at me.',
  'I want to learn ASL.',
  'My family is here.',
  'Please open the door.',
  'Please close the door.',
  'Where do you live?',
  'We study together.',
  'I have a question.',
  'Please answer me.',
  'Can you see me?',
  'I can help you.',
  'Do you understand now?',
  'I want to eat apple.',
  'I want to drink coffee.',
  'Please bring water.',
  'My friend will come today.',
  'Please sit here.',
  'I like this class.',
  'This teacher is nice.',
  'Where is my bag?',
  'I need my phone.',
  'Please write your name.',
  'Please read this book.',
  'My sister is at home.',
  'We go home now.',
  'I feel good today.',
  'I feel sick today.',
  'Please show me.',
  'Can we start now?',
  'I want to play today.',
  'The class starts now.',
  'My mother is kind.',
  'My father is strong.',
  'I am a student.',
  'She is my friend.',
  'He is a doctor.',
  'I like music.',
  'Do you like animals?',
  'The weather is cold today.',
  'I want to sleep.',
  'Please be careful.',
  'I forgot my book.',
  'She is very smart.',
  'We need more time.',
  'I am from America.',
  'Do you speak English?',
  'I like to cook.',
  'The movie was funny.',
  'Please eat your food.',
] as const;

export const RANDOM_SENTENCES = UNITY_RANDOM_SENTENCES;
