// Random sentence pool limited to curated examples whose gloss tokens
// map directly to SignController.cs signs after stripping dataset prefixes.
export const RANDOM_SENTENCES = [
  'Hello, everyone in class.',
  'Please take this book to class tomorrow.',
  'Tomorrow, please take my book to class.',
  'Is this your book for class tomorrow?',
  'Which book will you take tomorrow?',
  'Where will you take this book tomorrow?',
  'Please take coffee to class tomorrow.',
  'My child, please take this book.',
  'This ancient book is for my child.',
  'Tomorrow, everyone should take a book.',
  'Which book should everyone take to class?',
  'Hello, please take this book.',
  'This book is ancient and important.',
  'This alien book looks ancient.',
  'Please take this coffee to everyone.',
  'Tomorrow, this class needs a book.',
  'Where is my book for class tomorrow?',
  'Which class is tomorrow for you?',
  'Please take this book for everyone.',
  'This book is for you and my child.',
  'Everyone, please take this book tomorrow.',
  'Hello, which book is for class tomorrow?',
  'This coffee is for everyone tomorrow.',
  'Please take this ancient book to class.',
  'Where should my child take this book?',
  'Tomorrow, please take coffee and a book.',
  'Is this ancient book for class tomorrow?',
  'Which book is for you tomorrow?',
  'Please take this book and this coffee.',
  'Hello, everyone, this class is tomorrow.',
  'Is the class tomorrow?',
  'Is this your book?',
  'Which book is yours?',
  'Where is this book?',
  'Tomorrow, everyone is ready for class.',
  'Please take this bag and this book.',
  'My dad has an ancient camera.',
  'This baby has a banana and a bag.',
  'The angel and the alien are here.',
  'This animal is near the camp.',
  'The dandelion is near the camp.',
  'The danger is near the camp.',
  'The future class needs another book.',
  'Any child can take this book.',
  'Please answer this ancient question.',
  'This balance is important for class.',
  'Hello, how are you today?',
  'Please help me with this book.',
  'Where is my coffee?',
  'Is this class for you?',
  'Please take this with you.',
  'Which one do you want?',
  'This is my book.',
  'That is your class.',
  'Please come here tomorrow.',
  'Where are you going tomorrow?',
  'My child needs this book.',
  'Please bring coffee to class.',
  'Is this your coffee?',
  'Which book do you need?',
  'Please tell everyone tomorrow.',
  'This is for my child.',
  'Where is everyone today?',
  'Please take this book home.',
  'Is this book for class?',
  'Please answer me tomorrow.',
  'My camera is in this bag.',
  'Please bring my bag tomorrow.',
  'This banana is for my child.',
  'Is this the right class?',
  'Please take this camera.',
  'Everyone is here for class.',
  'Where is my bag?',
  'Please bring this book back.',
  'Which class do you want?',
  'This is important for tomorrow.',
] as const;
