using System.Runtime.CompilerServices;

#if GENIES_SDK && !GENIES_INTERNAL
[assembly: InternalsVisibleTo("Genies.Login.Native.Editor")]
[assembly: InternalsVisibleTo("Native.Login.Samples")]
[assembly: InternalsVisibleTo("Genies.Telemetry")]
[assembly: InternalsVisibleTo("Genies.AvatarEditor")]
[assembly: InternalsVisibleTo("Genies.Avatars.Context")]
[assembly: InternalsVisibleTo("Genies.Avatars.Sdk")]
[assembly: InternalsVisibleTo("Genies.Avatars.Services")]
[assembly: InternalsVisibleTo("Genies.CloudSave")]
[assembly: InternalsVisibleTo("Genies.Closet")]
[assembly: InternalsVisibleTo("Genies.Cms")]
[assembly: InternalsVisibleTo("Genies.Dynamics")]
[assembly: InternalsVisibleTo("Genies.Inventory")]
[assembly: InternalsVisibleTo("Genies.FeatureFlags")]
[assembly: InternalsVisibleTo("Genies.Looks")]
[assembly: InternalsVisibleTo("Genies.Leaderboard")]
[assembly: InternalsVisibleTo("Genies.Naf.Addressables")]
[assembly: InternalsVisibleTo("Genies.Naf.Content")]
[assembly: InternalsVisibleTo("Genies.Sdk.Avatar")]
[assembly: InternalsVisibleTo("Genies.Sdk.Bootstrap.Editor")]
[assembly: InternalsVisibleTo("Genies.GraphqlClient")]
[assembly: InternalsVisibleTo("Genies.Multiplayer.Editor")]
[assembly: InternalsVisibleTo("Genies.Multiplayer")]
[assembly: InternalsVisibleTo("Genies.Experience.CloudSave")]
[assembly: InternalsVisibleTo("Genies.Experience.Sdk.Editor")]
[assembly: InternalsVisibleTo("Genies.Experience.Client")]
[assembly: InternalsVisibleTo("Genies.Experience.Sdk")]
[assembly: InternalsVisibleTo("Genies.Experience.Core")]
[assembly: InternalsVisibleTo("Genies.Sdk.Core")]
[assembly: InternalsVisibleTo("Genies.Services")]
[assembly: InternalsVisibleTo("Genies.Services.DynamicConfigs")]
[assembly: InternalsVisibleTo("Genies.Ugc")]
[assembly: InternalsVisibleTo("Genies.Wearables")]
[assembly: InternalsVisibleTo("Genies.Social")]
[assembly: InternalsVisibleTo("Genies.Friends")]
#endif
